import MacrosForStroblMocks
import XCTest
@testable import MacrosForStroblMocksClient

@UsesStroblMocks
final class Test03MockWithoutCalledMethodsProperty: XCTestCase {
    
    @StroblMock var mock: MockWithoutCalledMethodsProperty!
    
    override func setUpWithError() throws {
        mock = MockWithoutCalledMethodsProperty()
    }
    
    func testMockWithoutCalledMethodsPropertyCausesVerifyStroblMocksUnusedToFailWithNonStroblMockMessage() {
        let expectedDescription = "failed - 'mock' does not appear to be a Strobl Mock. Neither 'calledMethods' or 'calledStaticMethods' properties were found."
        let options = XCTExpectedFailure.Options()
        options.issueMatcher = { issue in
            issue.type == .assertionFailure && issue.compactDescription == expectedDescription
        }

        // Test needs to be run to get failure.
        // It should result in the following message:
        //
        //       'mock' does not appear to be a Strobl Mock. Neither 'calledMethods' or 'calledStaticMethods' properties were found.
        //
        XCTExpectFailure("This text exercises code generated by @UsesStroblMocks and should fail", options: options)
        verifyStroblMocksUnused()
        
    }

}
